config/routes.rb
Rails.application.routes.draw do
  root "sessions#new"
  post 'login', :to => 'sessions#create'
  get 'logout', :to => 'sessions#destroy'
  get 'new_product', :to => 'products#new'
  post 'bulk_upload', :to => 'products#bulk_upload'
  post 'create_product', :to => 'products#create'
  post 'create_brand_segment', :to => 'brand_segments#create'
  post 'create_brand', :to => 'brands#create'
  get 'products', :to => 'products#index'
  get 'edit_products/:id', :to => 'products#edit'
  get 'delete_products/:id', :to => 'products#destroy'
  resources "users"
  resources "products"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :brand_segments
  has_many :product

  validates :brand_name, presence: true, uniqueness: true
end

app/models/brand_segment.rb
class BrandSegment < ApplicationRecord
  belongs_to :brand
  validates :segment, presence: true, uniqueness: true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :brand_segment
  belongs_to :brand

end

app/models/user.rb
class User < ApplicationRecord
  enum :role, [ :admin, :iba ]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :info, :error, :warning

  def get_input_data
    @brands = Brand.pluck(:brand_name, :id)
    @segments = BrandSegment.pluck(:segment, :id)    
  end

  private   
  def current_user   
    @current_user = session[:user_id].present? ? User.find(session[:user_id]) : nil
    unless @current_user
      redirect_to root_path , notice: "Book not found"  
    end  
  end   
  helper_method :current_user   
end

app/controllers/brand_segments_controller.rb
class BrandSegmentsController < ApplicationController
  def create
    segment = BrandSegment.new(segment: params['segment'], brand_id: params['brand_id'])
    if segment.save
      redirect_to new_product_path, notice: "segment Added"
    else
      redirect_to new_product_path, notice: segment.errors.full_messages
    end
  end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  def create
    brand = Brand.new(brand_name: params['brand_name'])
    if brand.save
      redirect_to new_product_path, notice: "Brand Added"
    else
      redirect_to new_product_path, notice: brand.errors.full_messages
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :get_input_data, only: [:new, :edit]
  require 'csv'

  def index
    @products = Product.includes(:brand, :brand_segment)
  end

  def new
    @product = Product.new
  end

  def create
    product = Product.new(product_params)
    if product.save
      redirect_to new_product_path, notice: "Product Added"
    else
      redirect_to new_product_path, notice: product.errors.full_messages
    end
  end

  def edit
    @product = Product.find_by_id(params['id'])
  end

  def update
    @product = Product.find_by_id(params['id'])
    if @product.update(product_params)
      redirect_to products_path, notice: "Product Updated"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    product = Product.find_by_id(params['id'])
    if product.delete
      redirect_to products_path, notice: "Product Deleted"
    else
      render :index, notice: product.errors.full_messages
    end
  end

  def bulk_upload
    if params[:file].present?
      begin
        product = []
        CSV.foreach(params[:file].path, headers: true) do |row|
          product << { brand_id: row['brand_id'], brand_segment_id: row["brand_segment_id"], model_no: row["model_no"],  product_detail: row["product_detail"], warranty_details: row["warranty_details"], price: row["price"], review_video_link: row["review_video_link"] }
        end
        product = Product.create!(product)
        redirect_to new_product_path, notice: "#{product.count} : Bulk Product Added"
      rescue StandardError => e
        redirect_to new_product_path, notice: "Error importing file: #{e.message}" 
      end
    else
      flash[:error] = "Please upload a file"
      redirect_to new_product_path
    end
  end  

  private
  def product_params
    params.require(:product).permit(:brand_id, :brand_segment_id, :model_no, :product_detail, :warranty_details, :price, :review_video_link)    
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    login_user = User.find_by(email: params['email'], password: params['password'])
    if login_user
      session[:user_id] = login_user.id
      redirect_to users_path, notice: "logged in"
    else
      redirect_to root_path
    end
  end

  def destroy
    session[:user_id] = nil   
    redirect_to root_url   
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :current_user
  def index
    @users = User.all    
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |type, msg| %>
  <div class="alert alert-info">
    <%= msg %>
  </div>
<% end %>

<script type="text/javascript">
  setTimeout(function(){
    $('.alert').css("display", "none");
  },5000);
</script>

app/views/layouts/_footer.html.erb
<% if current_user.present? %>
  <div class="text-light navbar-expand-lg navbar-dark bg-dark" id="last-footer">
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3  border-top">
      <div class="col-md-4 d-flex align-items-center">
        <span href="/" class="mb-3 me-2 mx-5 mb-md-0 text-body-secondary text-decoration-none lh-1">
          We-IBas
        </span>
        <span class="mb-3 mb-md-0 text-body-secondary">© 2024 Company, Inc</span>
      </div>

      <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
        <li class="ms-3 mx-3"><a class="text-body-secondary" href="#"><svg xmlns="http://www.w3.org/2000/svg" 
          width="16" height="16" fill="currentColor" class="bi bi-twitter-x" viewBox="0 0 16 16">
          <path d="M12.6.75h2.454l-5.36 6.142L16 15.25h-4.937l-3.867-5.07-4.425 5.07H.316l5.733-6.57L0 .75h5.063l3.495 4.633L12.601.75Zm-.86 13.028h1.36L4.323 2.145H2.865z"/>
        </svg></a></li>
        <li class="ms-3 mx-3"><a class="text-body-secondary" href="#"><svg xmlns="http://www.w3.org/2000/svg" 
          width="16" height="16" fill="currentColor" class="bi bi-instagram" viewBox="0 0 16 16">
          <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.9 3.9 0 0 0-1.417.923A3.9 3.9 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.9 3.9 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.9 3.9 0 0 0-.923-1.417A3.9 3.9 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599s.453.546.598.92c.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.5 2.5 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.5 2.5 0 0 1-.92-.598 2.5 2.5 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233s.008-2.388.046-3.231c.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92s.546-.453.92-.598c.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92m-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217m0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334"/>
        </svg></a></li>
        <li class="ms-3 mx-3"><a class="text-body-secondary" href="#"><svg xmlns="http://www.w3.org/2000/svg" 
          width="16" height="16" fill="currentColor" class="bi bi-facebook" viewBox="0 0 16 16">
          <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951"/>
        </svg></a></li>
        <li class="ms-3 mx-3"><a class="text-body-secondary" href="#"><svg xmlns="http://www.w3.org/2000/svg" 
          width="16" height="16" fill="currentColor" class="bi bi-whatsapp" viewBox="0 0 16 16">
          <path d="M13.601 2.326A7.85 7.85 0 0 0 7.994 0C3.627 0 .068 3.558.064 7.926c0 1.399.366 2.76 1.057 3.965L0 16l4.204-1.102a7.9 7.9 0 0 0 3.79.965h.004c4.368 0 7.926-3.558 7.93-7.93A7.9 7.9 0 0 0 13.6 2.326zM7.994 14.521a6.6 6.6 0 0 1-3.356-.92l-.24-.144-2.494.654.666-2.433-.156-.251a6.56 6.56 0 0 1-1.007-3.505c0-3.626 2.957-6.584 6.591-6.584a6.56 6.56 0 0 1 4.66 1.931 6.56 6.56 0 0 1 1.928 4.66c-.004 3.639-2.961 6.592-6.592 6.592m3.615-4.934c-.197-.099-1.17-.578-1.353-.646-.182-.065-.315-.099-.445.099-.133.197-.513.646-.627.775-.114.133-.232.148-.43.05-.197-.1-.836-.308-1.592-.985-.59-.525-.985-1.175-1.103-1.372-.114-.198-.011-.304.088-.403.087-.088.197-.232.296-.346.1-.114.133-.198.198-.33.065-.134.034-.248-.015-.347-.05-.099-.445-1.076-.612-1.47-.16-.389-.323-.335-.445-.34-.114-.007-.247-.007-.38-.007a.73.73 0 0 0-.529.247c-.182.198-.691.677-.691 1.654s.71 1.916.81 2.049c.098.133 1.394 2.132 3.383 2.992.47.205.84.326 1.129.418.475.152.904.129 1.246.08.38-.058 1.171-.48 1.338-.943.164-.464.164-.86.114-.943-.049-.084-.182-.133-.38-.232"/>
        </svg></a></li>
      </ul>
    </footer>
  </div>
<% end %>

app/views/layouts/_sidebar.html.erb
<% if @current_user.present? %>
  <div class="col-md-2 sidebar"> <!-- Set col-md-2 for 20% width -->
    <h2>Ecom-Shopee</h2>
    <div class="nav-div">
      <ul class="navbar-nav navbar-right">
        <li class="nav-item dropdown">
          <a href="/new_product" class="nav-links">New Product</a>
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown1" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Product Updation
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown1">
            <a class="dropdown-item" href="/products">All Products</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>

          <%= link_to "User | #{@current_user&.name.humanize} : #{@current_user.id}", "#", class: "nav-link dropdown-toggle text-light", id: "navbarDropdown", role: "button", data: { toggle: "dropdown" }, aria: { haspopup: "true", expanded: "false" } %>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "Logout", logout_path, class: "dropdown-item" %>
          </div>
        </li>
      </ul>
    </div>
  </div>


<% end %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IBA</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag 'external' %>
    <%= stylesheet_link_tag "style.css" %>
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script> -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>

  <body>
    <div class="container-fluid">
      <%= render partial: "layouts/flash" %>
      <div class="row">
        <!-- Sidebar -->
        <%= render partial: "layouts/sidebar" %>
        <!-- Main Section -->
        <div class="col-md-10 main-section"> <!-- Set col-md-10 for remaining width -->
          <%= yield %>
        </div>
      </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

app/views/products/_add_brand.html.erb
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Add New Brand</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_with(url: create_brand_path, method: :post) do |form| %>
          <div class="form-group">
            <label for="exampleFormControlTextarea1">Add Brand Name</label>
            <%= form.text_field :brand_name, {class: "form-control", id: "exampleFormControlTextarea1"} %>
          </div>
          <div class="modal-footer">
              <%= form.button "Submit", class: "btn btn-primary", type: "submit" %>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/products/_add_segment.html.erb
<div class="modal fade" id="exampleModalCenterSegment" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Add New Product Segment</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_with(url: create_brand_segment_path, method: :post) do |form| %>
          <div class="form-group">
            <label for="exampleFormControlSelect1">Brands</label>
           <%= form.select 'brand_id', options_for_select(@brands), { id: "exampleFormControlSelect1", class: "form-control" } %>
          </div>
          <div class="form-group">
            <label for="exampleFormControlTextarea1">Segment</label>
            <%= form.text_field :segment, {class: "form-control", id: "exampleFormControlTextarea1"} %>
          </div>
          <div class="modal-footer">
              <%= form.button "Submit", class: "btn btn-primary", type: "submit" %>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/products/_bulk_product_upload.html.erb
<div class="modal fade" id="exampleModalCenterBulkUpload" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Add CSV File To Bulk Prodcut Upload.</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_with(url: bulk_upload_path, method: :post) do |form| %>
          <div class="form-group">
            <label for="exampleFormControlTextarea1">Upload Product CSV File:</label>
            <%= form.file_field :file, { accept: "text/csv", class: "form-control", id: "exampleFormControlTextarea1" } %>
          </div>
          <div class="modal-footer">
              <%= form.button "Submit", class: "btn btn-primary", type: "submit" %>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/products/edit.html.erb
<%= form_for @product do |f| %>
  
  <div class="form-group">
    <%= f.label :brand_id %>
    <%= f.collection_select :brand_id, @brands, :last, :first, { prompt: "Select Brand" }, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :brand_segment_id %>
    <%= f.collection_select :brand_segment_id, @segments, :last, :first, { prompt: "Select Segment" }, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :model_no %>
    <%= f.text_field :model_no, value: @product.model_no, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :product_detail %>
    <%= f.text_field :product_detail, value: @product.product_detail, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :warranty_details %>
    <%= f.text_field :warranty_details, value: @product.warranty_details, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :price %>
    <%= f.number_field :price, value: @product.price, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :review_video_link %>
    <%= f.text_field :review_video_link, value: @product.review_video_link, class: "form-control" %>
  </div>
  <!-- Add other form fields as needed -->

  <div class="actions">
    <%= f.submit "Update", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/products/index.html.erb
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Brand</th>
      <th scope="col">Segment</th>
      <th scope="col">Model</th>
      <th scope="col">Product Details</th>
      <th scope="col">Warranty Details</th>
      <th scope="col">Price</th>
      <th scope="col">Review Video Link</th>
      <th scope="col">Action</th>

    </tr>
  </thead>
  <tbody>
  	<% @products.each do |product| %>
      <tr>
        <td><%= product.id %></td>
        <td><%= product.brand_id %> : <%= product.brand.brand_name%></td>
        <td><%= product.brand_segment_id %> : <%= product.brand_segment.segment%></td>
        <td><%= product.model_no %></td>
        <td><%= product.product_detail %></td>
        <td><%= product.warranty_details %></td>
        <td><%= product.price %></td>
        <td><%= product.review_video_link %></td>
        <td>
          <%= link_to "Edit", edit_product_path(product.id), class: "btn btn-primary btn-sm" %>
          <%= link_to "Delete", "/delete_products/#{product.id}", data: { confirm: "Are you sure you want to delete this product?" }, class: "btn btn-danger btn-sm ml-1" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/products/new.html.erb
<%= form_for @product, method: :post do |form| %>
  <h1 class="text-center">Ecom-Shopees</h1>
  <a href="#", data-toggle="modal" data-target="#exampleModalCenterBulkUpload">Bulk Upload Product</a>
  <div class="form-group">
    <label for="exampleFormControlSelect1">Brands <a href="#", data-toggle="modal" data-target="#exampleModalCenter">Add Brand</a> </label>
   <%= form.select 'brand_id', options_for_select(@brands), { id: "exampleFormControlSelect1", class: "form-control" } %>
  </div>

  <div class="form-group">
    <label for="exampleFormControlSelect1">Brand Segment <a href="#", data-toggle="modal" data-target="#exampleModalCenterSegment">Add Segment</a></label>
   <%= form.select 'brand_segment_id', options_for_select(@segments), { id: "exampleFormControlSelect1", class: "form-control" } %>
  </div>
  <div class="form-group">
    <label for="exampleFormControlTextarea1">Model</label>
    <%= form.text_field :model_no, {class: "form-control", id: "exampleFormControlTextarea1"} %>
  </div>
  <div class="form-group">
    <label for="exampleFormControlTextarea1">Product Detail</label>
    <%= form.text_field :product_detail, {class: "form-control", id: "exampleFormControlTextarea1"} %>
  </div>
  <div class="form-group">
    <label for="exampleFormControlTextarea1">Warranty Detail</label>
    <%= form.text_field :warranty_details, {class: "form-control", id: "exampleFormControlTextarea1"} %>
  </div>
  <div class="form-group">
    <label for="exampleFormControlTextarea1">Price</label>
    <%= form.text_field :price, {class: "form-control", id: "exampleFormControlTextarea1"} %>
  </div>
  <div class="form-group">
    <label for="exampleFormControlTextarea1">Review Video Link</label>
    <%= form.text_field :review_video_link, {class: "form-control", id: "exampleFormControlTextarea1"} %>
  </div>
  <div class="login-buttons">
    <%= form.button "Submit", class: "btn btn-primary", type: "submit" %>
  </div>
<% end %>
<%= render partial: "products/add_segment" %>
<%= render partial: "products/add_brand" %>
<%= render partial: "products/bulk_product_upload" %>

app/views/users/show.html.erb
Hello show